language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project NeuralNetwork.xcodeproj -scheme NeuralNetwork
- xctool test -project NeuralNetwork.xcodeproj -scheme NNTests
